global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'scmd-api'
    static_configs:
      - targets: ['api:3000']
        labels:
          service: 'scmd-api'
    metrics_path: '/api/v1/monitor/metrics'
  
  - job_name: 'scmd-worker-heavy'
    static_configs:
      - targets: ['worker-heavy:3000']
        labels:
          service: 'scmd-worker-heavy'
    metrics_path: '/api/v1/monitor/metrics'

  - job_name: 'scmd-worker-light'
    static_configs:
      - targets: ['worker-light:3000']
        labels:
          service: 'scmd-worker-light'
    metrics_path: '/api/v1/monitor/metrics'
